### PR TITLE
No global state

### PR DESCRIPTION
**Pull request by gmalouf**
This pr removes the hard dependency on play's global state.  Users can now mix this library into play apps using compile-time (and run-time) dependency injection.  Settings are now centralized into a single configuration class where all of the validation takes place at initialization.

### CODE REVIEW

**Comment by chrisnappin** [comment]
Hi, many thanks for the contribution. I'd like to merge in this and the other recent pull request and put out a new release for Play 2.5.

What would the client code look like with this change? Now that the template needs an implicit widgetHelper, in order to get the "ExampleForm" Controller to compile I've had to add implicit parameters as follows:

def show = Action { implicit request =>
        Ok(views.html.form(userForm)(request, messagesApi.preferred(request), widgetHelper))
    }

Is there not a better way of doing this?

**Comment by gmalouf** [comment]
I made the widget helper an implicit parameter to my controller.

class MyAwesomeController(various explicit params...)(implicit
widgetHelper: WidgetHelper, ex: ExecutionContext)

Any views that then depend on the helper have it available via their own
implicit parameters list.

(in view)

@(signInForm: Form[display.SignInData])(implicit
recaptchaWidgetHelper: WidgetHelper,
request: Request[AnyContent], messages: Messages)

For the most part we are not having to explicitly specify the implicit
parameters when calling the view from a controller as you are in your
example above.  You have to be able to pass the WidgetHelper since there is
no longer any global state...

**Comment by chrisnappin** [comment]
Brilliant, I've merged in these code changes. Thanks again.

**Comment by gmalouf** [comment]
Happy to help, we love the recaptcha on our app.

**Pull request merged**
