### PR TITLE
Upgrade to Play 2.6

### PR DESCRIPTION
**Pull request by akitaylor**
Hi Chris!

I have done the upgrade to Play 2.6.0, please check if it is ok. All tests are running, but I could not try it it in a real application yet.

Regards,
Akos

### CODE REVIEW

**Comment by chrisnappin** [comment]
Great, many thanks. I'll take a look once I've finished off the new functionality for the upcoming release, which I'd like to retain compatibility with Play 2.5

**Comment by chrisnappin** [comment]
I've merged this in, thanks again.

**Comment by akitaylor** [comment]
Can you estimate the time of the release for play 2.6? 
Thanks!

**Comment by chrisnappin** [comment]
Hi, I have some tests to finish off for my simple nonce implementation (as Play 2.6 enabled CSP by default) then some documentation updates detailing how I've changed the API with 2.6 features, so hopefully later this week!

**Comment by akitaylor** [comment]
That's great! Thanks

**Pull request closed without merging**
